/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domain.Korisnik;
import domain.Prijava;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author matij
 */
public class FrmPrikazPrijava extends javax.swing.JFrame {

    private Korisnik ulogovani;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrikazPrijava.class.getName());

    /**
     * Creates new form FrmPrikazPrijava
     */
    public FrmPrikazPrijava(Korisnik k) {
        initComponents();
        this.ulogovani = k;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pripremiTabelu();

    }

    private FrmPrikazPrijava() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void pripremiTabelu() {
        try {
            List<Prijava> mojePrijave = communication.Communication.getInstance().getUserApplications(ulogovani);

            ModelTabeleKlijent model = new ModelTabeleKlijent(mojePrijave);
            tblPrijave.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrijave = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moje prijave");

        tblPrijave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrijave);

        jButton1.setText("Zatvori");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnOtkazi.setText("Otkaži prijavu");
        btnOtkazi.addActionListener(this::btnOtkaziActionPerformed);

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(this::btnIzmeniActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOtkazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnOtkazi)
                    .addComponent(btnIzmeni))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        int red = tblPrijave.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati prijavu iz tabele!");
            return;
        }

        ModelTabeleKlijent model = (ModelTabeleKlijent) tblPrijave.getModel();
        Prijava odabrana = model.getPrijavaAt(red);
        String status = (String) model.getValueAt(red, 4);

        if (status.equals("ZAKLJUČANA") || status.equals("ZAVRŠENA")) {
            JOptionPane.showMessageDialog(this, "Ne možete otkazati prijavu koja je završena ili počinje za manje od 24h!");
            return;
        }

        try {
            int odluka = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da otkažete prijavu?");
            if (odluka == JOptionPane.YES_OPTION) {
                communication.Communication.getInstance().otkaziPrijavu(odabrana);

                JOptionPane.showMessageDialog(this, "Uspešno otkazano.");
                pripremiTabelu();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage());
        }
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        int red = tblPrijave.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Odaberite prijavu!");
            return;
        }

        ModelTabeleKlijent model = (ModelTabeleKlijent) tblPrijave.getModel();
        Prijava odabrana = model.getPrijavaAt(red);

        String status = (String) model.getValueAt(red, 4);
        if ("ZAKLJUČANA".equals(status) || "ZAVRŠENA".equals(status)) {
            JOptionPane.showMessageDialog(this, "Ne možete menjati prijavu koja je zaključana ili završena!");
            return;
        }

        FrmPrijava frm = new FrmPrijava(ulogovani, odabrana);
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                pripremiTabelu();
            }
        });
        frm.setVisible(true);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrikazPrijava().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrijave;
    // End of variables declaration//GEN-END:variables
}
