/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domain.Korisnik;
import domain.Pozicija;
import domain.Prijava;
import domain.Smena;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author matij
 */
public class FrmPrijava extends javax.swing.JFrame {

    private final Korisnik ulogovani;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrijava.class.getName());
    private Prijava prijavaZaIzmenu = null;

    /**
     * Creates new form FrmPrijava
     */
    public FrmPrijava(Korisnik k) {
        initComponents();
        this.ulogovani = k;
        setTitle("Prijava za volontiranje - " + ulogovani.getIme() + " " + ulogovani.getPrezime());
        lblDobrodosli.setText("Dobrodošli, " + ulogovani.getIme());
        popuniComboBoxeve();
    }
// Konstruktor za IZMENU

    public FrmPrijava(Korisnik k, Prijava p) {
        this(k);
        this.prijavaZaIzmenu = p;

        setTitle("Izmena prijave");
        btnPosalji.setText("SAČUVAJ IZMENE");

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumVolontiranja.setText(sdf.format(p.getDatumVolontiranja()));
        cmbSmena.setSelectedItem(p.getSmena());
        cmbPozicija.setSelectedItem(p.getPozicija());
    }

    private FrmPrijava() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void popuniComboBoxeve() {
        cmbSmena.setModel(new DefaultComboBoxModel<>(Smena.values()));
        cmbPozicija.setModel(new DefaultComboBoxModel<>(Pozicija.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDatumVolontiranja = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbSmena = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPozicija = new javax.swing.JComboBox<>();
        btnPosalji = new javax.swing.JButton();
        lblDobrodosli = new javax.swing.JLabel();
        btnMojePrijave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Korisnički panel");

        jLabel1.setText("Datum");

        jLabel2.setText("Smena");

        jLabel3.setText("Pozicija");

        btnPosalji.setText("Posalji");
        btnPosalji.addActionListener(this::btnPosaljiActionPerformed);

        lblDobrodosli.setText("Korisnik nije ulogovan!!!");

        btnMojePrijave.setText("Moje Prijave");
        btnMojePrijave.addActionListener(this::btnMojePrijaveActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatumVolontiranja, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cmbSmena, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPosalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblDobrodosli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMojePrijave)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDobrodosli)
                    .addComponent(btnMojePrijave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumVolontiranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSmena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPosalji))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiActionPerformed
        try {
            if (txtDatumVolontiranja.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate uneti datum!");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            sdf.setLenient(false);
            Date datumVol = sdf.parse(txtDatumVolontiranja.getText());

            Date danas = new Date();
            Date finale = sdf.parse("01.02.2026");

            if (datumVol.before(danas)) {
                JOptionPane.showMessageDialog(this, "Datum volontiranja mora biti u budućnosti!");
                return;
            }
            if (datumVol.after(finale)) {
                JOptionPane.showMessageDialog(this, "Turnir se završava 01.02.2026!");
                return;
            }

            Prijava p;

            if (this.prijavaZaIzmenu != null) {
                p = this.prijavaZaIzmenu;
            } else {
                p = new Prijava();
                p.setId(UUID.randomUUID().toString());
                p.setKorisnik(ulogovani);
                p.setDatumPrijave(new Date());
                p.setStatus("Na čekanju");
            }

            p.setDatumVolontiranja(datumVol);
            p.setSmena((Smena) cmbSmena.getSelectedItem());
            p.setPozicija((Pozicija) cmbPozicija.getSelectedItem());

            if (this.prijavaZaIzmenu != null) {
                communication.Communication.getInstance().editPrijava(p);
                JOptionPane.showMessageDialog(this, "Prijava uspešno izmenjena!");
                this.dispose();
            } else {
                communication.Communication.getInstance().addPrijava(p);

                kreirajPotvrduFajl(p);
                JOptionPane.showMessageDialog(this, "Uspešno ste se prijavili!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPosaljiActionPerformed

    private void btnMojePrijaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMojePrijaveActionPerformed
        // TODO add your handling code here:
        new FrmPrikazPrijava(ulogovani).setVisible(true);
    }//GEN-LAST:event_btnMojePrijaveActionPerformed
    private void kreirajPotvrduFajl(Prijava p) {
        try {
            String imeFajla = "potvrda_" + p.getKorisnik().getJmbg() + "_" + p.getId().substring(0, 5) + ".txt";

            FileWriter fw = new FileWriter(imeFajla);
            try (PrintWriter pw = new PrintWriter(fw)) {
                pw.println("=== POTVRDA PRIJAVE ZA VOLONTIRANJE ===");
                pw.println("Australian Open 2026");
                pw.println("=======================================");
                pw.println("Volonter: " + p.getKorisnik().getIme() + " " + p.getKorisnik().getPrezime());
                pw.println("JMBG: " + p.getKorisnik().getJmbg());
                pw.println("Email: " + p.getKorisnik().getEmail());
                pw.println("---------------------------------------");
                pw.println("Datum volontiranja: " + new SimpleDateFormat("dd.MM.yyyy").format(p.getDatumVolontiranja()));
                pw.println("Smena: " + p.getSmena());
                pw.println("Pozicija: " + p.getPozicija());
                pw.println("Datum slanja prijave: " + new SimpleDateFormat("dd.MM.yyyy HH:mm").format(p.getDatumPrijave()));
                pw.println("=======================================");
            }

        } catch (IOException ex) {
            System.out.println("Greška pri kreiranju fajla: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrijava().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMojePrijave;
    private javax.swing.JButton btnPosalji;
    private javax.swing.JComboBox<Pozicija> cmbPozicija;
    private javax.swing.JComboBox<Smena> cmbSmena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDobrodosli;
    private javax.swing.JTextField txtDatumVolontiranja;
    // End of variables declaration//GEN-END:variables
}
